name: 'clickhouse_starschema'
version: '1.0.4'
config-version: 2


profile: 'clickhouse_starschema'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"


models:
  clickhouse_starschema:
      +materialized: table
      staging:
          +materialized: table
          +tags: ['staging']
      star:
          +materialized: table
          +tags: ['star']
      test_query:
          +materialized: table
          +tags: ['homework']
